# 購入履歴情報を取得するための，Amazon.co.jp のログイン情報
login:
    amazon:
        user: Amazon.co.jp のユーザ名
        pass: Amazon.co.jp のパスワード

# データ収集で使用する一時ファイルの置き場所
data:
    # Web ブラウザの作業フォルダ
    selenium: data

    # デバッグ用のファイルを生成するフォルダ
    debug: data/debug

    # 購入履歴関係のデータ
    amazon:
        cache:
            # 収集した購入履歴情報 (どこまで取集したかの管理データ含む)
            order: data/amazon/cache.dat
            # サムネイル画像
            thumb: data/amazon/thumb

# 出力ファイルの置き場所
output:
    # 画像認証画像
    captcha: output/captcha.png

    excel:
        # フォント
        font:
            name: BIZ UDGothic
            size: 12
        # 購入履歴が記載されたファイル
        table: output/amazhist.xlsx
